room_menu_dialog_view=
{
	name="room_menu_dialog_view",type=0,typeName="View",time=0,x=0,y=0,width=720,height=1280,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,
	{
		name="room_menu_full_screen_bg",type=1,typeName="Image",time=11438763,x=0,y=0,width=720,height=1280,visible=0,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,file=""
	},
	{
		name="room_menu_dialog",type=1,typeName="Image",time=11438802,x=0,y=100,width=760,height=200,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,file="common/background/foldMenuBackground.png",gridLeft=100,gridRight=0,gridTop=0,gridBottom=20
	},
	{
		name="room_menu_dialog_bg",type=0,typeName="View",time=88855722,x=0,y=135,width=680,height=132,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,
		{
			name="room_menu_undo_btn",type=2,typeName="Button",time=11439135,x=-144,y=0,width=88,height=132,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,file="online/room/menu/undo_nor.png",file2="online/room/menu/undo_press.png"
		},
		{
			name="room_menu_draw_btn",type=2,typeName="Button",time=11439234,x=144,y=0,width=88,height=132,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,file="online/room/menu/draw_nor.png",file2="online/room/menu/draw_press.png"
		},
		{
			name="room_menu_surrender_btn",type=2,typeName="Button",time=11439369,x=0,y=0,width=88,height=132,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,file="online/room/menu/surrender_nor.png",file2="online/room/menu/surrender_press.png"
		},
		{
			name="room_menu_setting_btn",type=2,typeName="Button",time=11439369,x=288,y=0,width=88,height=132,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,file="online/room/menu/setting_nor.png",file2="online/room/menu/setting_press.png"
		},
		{
			name="roomMenuBackButton",type=2,typeName="Button",time=144483143,x=-288,y=0,width=88,height=132,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,file="common/button/exitBtnNor.png",file2="common/button/exitBtnPre.png"
		}
	}
}