collect_view=
{
	name="collect_view",type=0,typeName="View",time=0,x=0,y=0,width=480,height=800,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,
	{
		name="replay_view_bg",type=1,typeName="Image",time=2185898,x=0,y=0,width=480,height=800,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,file="drawable/state_texture_bg.png",gridLeft=32,gridRight=32,gridTop=32,gridBottom=32
	},
	{
		name="content_view",type=0,typeName="View",time=2186812,x=0,y=0,width=480,height=800,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignCenter,
		{
			name="content_holder",type=0,typeName="View",time=90562315,x=0,y=0,width=480,height=800,visible=1,fillParentWidth=0,fillParentHeight=1,nodeAlign=kAlignTop
		}
	},
	{
		name="title_view",type=0,typeName="View",time=2185935,x=0,y=0,width=0,height=0,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTopLeft,
		{
			name="title_bg",type=1,typeName="Image",time=2185963,x=0,y=0,width=480,height=95,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="common/activity_center_top_title_bg.png"
		},
		{
			name="back_btn",type=2,typeName="Button",time=2186615,x=0,y=3,width=62,height=62,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="common/ending_back.png"
		},
		{
			name="Image1",type=1,typeName="Image",time=93008542,x=0,y=0,width=372,height=65,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="common/ending_bg.png",
			{
				name="Image2",type=1,typeName="Image",time=93008609,x=0,y=0,width=195,height=38,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="replay/collect_title.png"
			}
		}
	}
}