console_lose_dialog_view=
{
	name="console_lose_dialog_view",type=0,typeName="View",time=0,x=0,y=0,width=0,height=0,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,
	{
		name="console_lose_dialog_full_screen_bg",type=1,typeName="Image",time=11499309,x=0,y=0,width=480,height=800,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,file="drawable/blank.png",gridLeft=1,gridRight=1,gridTop=1,gridBottom=1
	},
	{
		name="console_lose_content_view",type=0,typeName="View",time=11500965,x=0,y=108,width=480,height=75,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,
		{
			name="console_lose_dialog_bg",type=1,typeName="Image",time=11500981,x=1,y=67,width=480,height=505,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="drawable/console_lose_bg.png",gridLeft=64,gridRight=64,gridTop=64,gridBottom=64
		},
		{
			name="console_line_texture",type=1,typeName="Image",time=20489773,x=6,y=309,width=468,height=4,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="drawable/console_lose_line.png"
		},
		{
			name="console_lose_cloud_texture",type=1,typeName="Image",time=81917128,x=56,y=20,width=355,height=147,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="drawable/console_lose_cloud_texture.png",
			{
				name="console_lose_result_texture",type=1,typeName="Image",time=20490271,x=5,y=41,width=361,height=145,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="drawable/console_lose_result_texture.png"
			},
			{
				name="console_lose_sun_texture",type=1,typeName="Image",time=81917178,x=-6,y=42,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="ui/image.png"
			}
		},
		{
			name="console_lose_chest_tips",type=4,typeName="Text",time=81917806,x=0,y=248,width=480,height=25,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=25,textAlign=kAlignCenter,colorRed=230,colorGreen=230,colorBlue=230,string=[[你在"小试牛刀"中挑战失败]]
		},
		{
			name="console_lose_cancel_btn",type=2,typeName="Button",time=24572816,x=431,y=91,width=36,height=36,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="dialog/btn_close_up.png",file2="dialog/btn_close_dow.png"
		},
		{
			name="console_lose_title",type=4,typeName="Text",time=24573209,x=0,y=197,width=480,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=30,textAlign=kAlignCenter,colorRed=230,colorGreen=230,colorBlue=230,string=[[很遗憾]]
		},
		{
			name="console_lose_save_btn",type=2,typeName="Button",time=24574093,x=50,y=507,width=180,height=75,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="dialog/btn_neg_up.png",file2="dialog/btn_neg_down.png.png",gridLeft=64,gridRight=64,gridTop=0,gridBottom=0,
			{
				name="console_lose_save_text",type=4,typeName="Text",time=24574159,x=3,y=0,width=170,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=30,textAlign=kAlignCenter,colorRed=0,colorGreen=0,colorBlue=0,string=[[保存棋谱]]
			}
		},
		{
			name="console_lose_restart_btn",type=2,typeName="Button",time=24574215,x=254,y=507,width=180,height=75,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="dialog/btn_pos_up.png",file2="dialog/btn_pos_down.png",gridLeft=64,gridRight=64,gridTop=0,gridBottom=2,
			{
				name="console_lose_next_text",type=4,typeName="Text",time=24574925,x=3,y=0,width=170,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=30,textAlign=kAlignCenter,colorRed=0,colorGreen=0,colorBlue=0,string=[[继续游戏]]
			}
		},
		{
			name="console_reward_bg",type=1,typeName="Image",time=24661691,x=53,y=326,width=380,height=150,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="drawable/console_lose_bottom_bg.png",gridLeft=32,gridRight=32,gridTop=32,gridBottom=32,
			{
				name="console_life_texture",type=1,typeName="Image",time=24661774,x=141,y=32,width=88,height=81,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="drawable/ending_life_sub_texture.png"
			}
		}
	}
}