dapu_view=
{
	name="dapu_view",type=0,typeName="View",time=0,x=0,y=0,width=480,height=800,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,
	{
		name="dapu_view_bg",type=1,typeName="Image",time=16169048,x=0,y=0,width=0,height=0,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,file="drawable/state_texture_bg.png",gridLeft=32,gridRight=32,gridTop=32,gridBottom=32
	},
	{
		name="dapu_title_view",type=0,typeName="View",time=16168425,x=0,y=0,width=480,height=0,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTopLeft,
		{
			name="dapu_title_bg",type=1,typeName="Image",time=16168445,x=0,y=0,width=480,height=95,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="common/activity_center_top_title_bg.png"
		},
		{
			name="dapu_back_btn",type=2,typeName="Button",time=16168692,x=0,y=0,width=62,height=62,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="common/ending_back.png"
		},
		{
			name="dapu_del_btn",type=2,typeName="Button",time=16168728,x=4,y=4,width=60,height=60,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="drawable/gold_btn_bg.png",
			{
				name="dapu_del_text",type=4,typeName="Text",time=16168924,x=0,y=0,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=20,textAlign=kAlignCenter,colorRed=79,colorGreen=39,colorBlue=0,string=[[确定]]
			}
		},
		{
			name="dapu_edit_btn",type=2,typeName="Button",time=16168781,x=4,y=4,width=60,height=60,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="drawable/gold_btn_bg.png",
			{
				name="dapu_edit_text",type=4,typeName="Text",time=16168967,x=0,y=0,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=20,textAlign=kAlignCenter,colorRed=79,colorGreen=39,colorBlue=0,string=[[删除]]
			}
		},
		{
			name="dapu_cover_btn",type=2,typeName="Button",time=16351060,x=4,y=4,width=60,height=60,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="drawable/gold_btn_bg.png",
			{
				name="dapu_cover_text",type=4,typeName="Text",time=16351108,x=0,y=0,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=20,textAlign=kAlignCenter,colorRed=79,colorGreen=39,colorBlue=0,string=[[覆盖]]
			}
		},
		{
			name="dapu_type_toggle_view",type=0,typeName="RadioButtonGroup",time=80723738,x=0,y=0,width=350,height=68,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop
		}
	},
	{
		name="dapu_content_view",type=0,typeName="View",time=16169077,x=0,y=70,width=480,height=730,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTop,
		{
			name="dapu_local_placehold",type=1,typeName="Image",time=18069731,x=0,y=0,width=480,height=730,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="drawable/blank.png",
			{
				name="local_empty_view",type=0,typeName="View",time=18070452,x=0,y=0,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
				{
					name="local_empty_text",type=4,typeName="Text",time=18070265,x=0,y=302,width=480,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=30,textAlign=kAlignCenter,colorRed=224,colorGreen=219,colorBlue=140,string=[[本地暂无棋谱]]
				},
				{
					name="local_empty_tip",type=4,typeName="Text",time=18070050,x=0,y=339,width=480,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=20,textAlign=kAlignCenter,colorRed=224,colorGreen=219,colorBlue=140,string=[[请到联网游戏中保存棋谱]]
				}
			}
		},
		{
			name="dapu_net_placehold",type=1,typeName="Image",time=16169111,x=0,y=0,width=480,height=730,visible=0,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="drawable/blank.png",
			{
				name="net_empty_text",type=4,typeName="Text",time=16341818,x=102,y=302,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=30,textAlign=kAlignCenter,colorRed=227,colorGreen=219,colorBlue=140,string=[[即将开放，敬请期待！]]
			}
		}
	}
}