hall_chat_dialog_view=
{
	name="hall_chat_dialog_view",type=0,typeName="View",time=0,x=0,y=0,width=720,height=1280,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,
	{
		name="bg",type=1,typeName="Image",time=97669571,x=-14,y=0,width=720,height=1080,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="common/background/dialog_bg_2.png",gridLeft=50,gridRight=50,gridTop=50,gridBottom=50,
		{
			name="hide_chat_btn",type=2,typeName="Button",time=99713426,x=520,y=-42,width=174,height=57,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="common/button/hide_chat_normal.png"
		},
		{
			name="main_chat",type=0,typeName="View",time=97725224,x=0,y=0,width=610,height=970,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,
			{
				name="title",type=0,typeName="View",time=97725795,x=0,y=0,width=610,height=75,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTop,
				{
					name="title_txt",type=4,typeName="Text",time=97725826,x=0,y=0,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,fontSize=42,textAlign=kAlignCenter,colorRed=80,colorGreen=80,colorBlue=80,string=[[聊天]]
				},
				{
					name="line",type=1,typeName="Image",time=97725918,x=0,y=0,width=607,height=19,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignBottom,file="common/decoration/line.png"
				},
				{
					name="add_chat",type=2,typeName="Button",time=97726557,x=-7,y=-8,width=80,height=75,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="drawable/blank.png",file2="drawable/blank.png",
					{
						name="icon",type=1,typeName="Image",time=98945670,x=0,y=0,width=34,height=34,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="common/button/create_chat_normal.png"
					}
				}
			},
			{
				name="content_view",type=0,typeName="View",time=97726088,x=0,y=0,width=200,height=880,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignBottom,
				{
					name="border",type=1,typeName="Image",time=97726099,x=55,y=-27,width=128,height=128,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,file="common/background/line_bg.png",gridLeft=50,gridRight=50,gridTop=50,gridBottom=50
				}
			}
		},
		{
			name="create_chat",type=0,typeName="View",time=97725412,x=0,y=0,width=610,height=970,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,
			{
				name="title",type=0,typeName="View",time=97727239,x=0,y=0,width=186,height=75,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTop,
				{
					name="title_txt",type=4,typeName="Text",time=97727240,x=0,y=0,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,fontSize=42,textAlign=kAlignCenter,colorRed=80,colorGreen=80,colorBlue=80,string=[[创建会话]]
				},
				{
					name="line",type=1,typeName="Image",time=97727241,x=0,y=0,width=607,height=19,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignBottom,file="common/decoration/line.png"
				},
				{
					name="back_btn",type=2,typeName="Button",time=97727242,x=0,y=0,width=55,height=55,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="drawable/blank.png",file2="drawable/blank.png",
					{
						name="icon",type=1,typeName="Image",time=98945811,x=0,y=0,width=35,height=33,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="common/button/back_normal.png"
					}
				}
			},
			{
				name="search_view",type=0,typeName="View",time=97810572,x=0,y=75,width=0,height=110,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTopLeft,
				{
					name="search_bg",type=1,typeName="Image",time=97810573,x=0,y=0,width=521,height=62,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="common/background/input_bg_2.png",gridLeft=25,gridRight=25,gridTop=25,gridBottom=25,
					{
						name="search_content",type=6,typeName="EditText",time=97810574,x=16,y=0,width=495,height=55,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,fontSize=32,textAlign=kAlignLeft,colorRed=80,colorGreen=80,colorBlue=80,string=[[]]
					}
				},
				{
					name="search_btn",type=2,typeName="Button",time=97810575,x=0,y=0,width=66,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="common/button/round_normal.png",file2="common/button/round_press.png",
					{
						name="search_img",type=1,typeName="Image",time=97810576,x=-2,y=12,width=36,height=39,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="dialog/search_enable_normal.png"
					}
				}
			},
			{
				name="content_view",type=0,typeName="View",time=97727306,x=0,y=0,width=200,height=770,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignBottom,
				{
					name="border",type=1,typeName="Image",time=97727307,x=0,y=0,width=610,height=770,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,file="common/background/line_bg.png",gridLeft=50,gridRight=50,gridTop=50,gridBottom=50
				},
				{
					name="item_up_mask",type=1,typeName="Image",time=97817280,x=0,y=1,width=594,height=60,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="common/decoration/item_up_mask.png"
				},
				{
					name="item_down_mask",type=1,typeName="Image",time=97817284,x=0,y=0,width=594,height=60,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,file="common/decoration/item_down_mas.png"
				}
			}
		},
		{
			name="member_list",type=0,typeName="View",time=97725432,x=0,y=0,width=610,height=970,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,
			{
				name="title",type=0,typeName="View",time=97727338,x=0,y=0,width=186,height=75,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTop,
				{
					name="title_txt",type=4,typeName="Text",time=97727339,x=0,y=0,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,fontSize=42,textAlign=kAlignCenter,colorRed=80,colorGreen=80,colorBlue=80,string=[[成员]]
				},
				{
					name="line",type=1,typeName="Image",time=97727340,x=0,y=0,width=607,height=19,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignBottom,file="common/decoration/line.png"
				},
				{
					name="back_btn",type=2,typeName="Button",time=98945917,x=0,y=0,width=55,height=55,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="drawable/blank.png",file2="drawable/blank.png",
					{
						name="icon",type=1,typeName="Image",time=98945918,x=0,y=0,width=35,height=33,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="common/button/back_normal.png"
					}
				}
			},
			{
				name="search_view",type=0,typeName="View",time=97727605,x=0,y=75,width=0,height=110,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTopLeft,
				{
					name="search_bg",type=1,typeName="Image",time=97727606,x=0,y=0,width=521,height=62,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="common/background/input_bg_2.png",gridLeft=25,gridRight=25,gridTop=25,gridBottom=25,
					{
						name="search_content",type=6,typeName="EditText",time=97727607,x=16,y=0,width=495,height=55,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,fontSize=32,textAlign=kAlignLeft,colorRed=80,colorGreen=80,colorBlue=80,string=[[]]
					}
				},
				{
					name="search_btn",type=2,typeName="Button",time=97727608,x=0,y=0,width=66,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="common/button/round_normal.png",file2="common/button/round_press.png",
					{
						name="search_img",type=1,typeName="Image",time=97727609,x=-2,y=12,width=36,height=39,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="dialog/search_enable_normal.png"
					}
				}
			},
			{
				name="content_view",type=0,typeName="View",time=97727376,x=0,y=0,width=200,height=770,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignBottom,
				{
					name="border",type=1,typeName="Image",time=97727377,x=55,y=-27,width=128,height=128,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,file="common/background/line_bg.png",gridLeft=50,gridRight=50,gridTop=50,gridBottom=50
				},
				{
					name="item_up_mask",type=1,typeName="Image",time=97817250,x=0,y=0,width=696,height=95,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTop,file="common/decoration/item_up_mask.png"
				},
				{
					name="item_down_mask",type=1,typeName="Image",time=97817254,x=0,y=0,width=696,height=95,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignBottom,file="common/decoration/item_down_mas.png"
				}
			}
		},
		{
			name="city_room_view",type=0,typeName="View",time=97725503,x=0,y=0,width=610,height=970,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,
			{
				name="title",type=0,typeName="View",time=97728126,x=0,y=0,width=186,height=75,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTop,
				{
					name="title_txt",type=4,typeName="Text",time=97728127,x=0,y=0,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,fontSize=42,textAlign=kAlignCenter,colorRed=80,colorGreen=80,colorBlue=80,string=[[深圳同城聊天室]]
				},
				{
					name="line",type=1,typeName="Image",time=97728128,x=0,y=0,width=607,height=19,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignBottom,file="common/decoration/line.png"
				},
				{
					name="check_member",type=2,typeName="Button",time=97728129,x=0,y=0,width=61,height=55,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="drawable/blank.png",file2="drawable/blank.png",
					{
						name="icon",type=1,typeName="Image",time=98946030,x=0,y=0,width=43,height=38,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="common/button/member_normal.png"
					}
				},
				{
					name="back_btn",type=2,typeName="Button",time=98945950,x=0,y=0,width=55,height=55,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="drawable/blank.png",file2="drawable/blank.png",
					{
						name="icon",type=1,typeName="Image",time=98945951,x=0,y=0,width=35,height=33,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="common/button/back_normal.png"
					}
				}
			},
			{
				name="content_view",type=0,typeName="View",time=97728272,x=0,y=0,width=200,height=770,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignCenter,
				{
					name="item_up_mask",type=1,typeName="Image",time=97728851,x=0,y=0,width=696,height=95,visible=0,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTop,file="common/decoration/item_up_mask.png"
				},
				{
					name="item_down_mask",type=1,typeName="Image",time=97728867,x=0,y=0,width=696,height=95,visible=0,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignBottom,file="common/decoration/item_down_mas.png"
				}
			},
			{
				name="bottom_view",type=0,typeName="View",time=97728378,x=0,y=0,width=200,height=105,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignBottom,
				{
					name="line",type=1,typeName="Image",time=97728396,x=0,y=0,width=607,height=19,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTop,file="common/decoration/line.png"
				},
				{
					name="send_bg",type=1,typeName="Image",time=97728556,x=0,y=0,width=470,height=61,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottomLeft,file="common/background/input_bg_2.png",gridLeft=25,gridRight=25,gridTop=25,gridBottom=25,
					{
						name="send_content",type=7,typeName="EditTextView",time=97982165,x=10,y=0,width=450,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,fontSize=32,textAlign=kAlignLeft,colorRed=80,colorGreen=80,colorBlue=80,string=[[]]
					}
				},
				{
					name="send_btn",type=2,typeName="Button",time=97728563,x=0,y=0,width=128,height=58,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottomRight,file="common/button/dialog_btn_3_normal.png",file2="common/button/dialog_btn_3_press.png",
					{
						name="send_txt",type=4,typeName="Text",time=97729214,x=0,y=-2,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=32,textAlign=kAlignLeft,colorRed=240,colorGreen=230,colorBlue=210,string=[[发送]]
					}
				}
			}
		},
		{
			name="dashi_room_view",type=0,typeName="View",time=97826644,x=0,y=0,width=610,height=970,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,
			{
				name="title",type=0,typeName="View",time=97826645,x=0,y=0,width=186,height=75,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTop,
				{
					name="title_txt",type=4,typeName="Text",time=97826646,x=0,y=0,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,fontSize=42,textAlign=kAlignCenter,colorRed=80,colorGreen=80,colorBlue=80,string=[[深圳同城聊天室]]
				},
				{
					name="line",type=1,typeName="Image",time=97826647,x=0,y=0,width=607,height=19,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignBottom,file="common/decoration/line.png"
				},
				{
					name="check_member",type=2,typeName="Button",time=98946102,x=0,y=0,width=61,height=55,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="drawable/blank.png",file2="drawable/blank.png",
					{
						name="icon",type=1,typeName="Image",time=98946103,x=0,y=0,width=43,height=38,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="common/button/member_normal.png"
					}
				},
				{
					name="back_btn",type=2,typeName="Button",time=98946111,x=0,y=0,width=55,height=55,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="drawable/blank.png",file2="drawable/blank.png",
					{
						name="icon",type=1,typeName="Image",time=98946112,x=0,y=0,width=35,height=33,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="common/button/back_normal.png"
					}
				}
			},
			{
				name="content_view",type=0,typeName="View",time=97826650,x=0,y=0,width=200,height=770,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignCenter,
				{
					name="item_up_mask",type=1,typeName="Image",time=97826651,x=0,y=0,width=696,height=95,visible=0,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTop,file="common/decoration/item_up_mask.png"
				},
				{
					name="item_down_mask",type=1,typeName="Image",time=97826652,x=0,y=0,width=696,height=95,visible=0,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignBottom,file="common/decoration/item_down_mas.png"
				}
			},
			{
				name="bottom_view",type=0,typeName="View",time=97826653,x=0,y=0,width=200,height=105,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignBottom,
				{
					name="line",type=1,typeName="Image",time=97826654,x=0,y=0,width=607,height=19,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTop,file="common/decoration/line.png"
				},
				{
					name="send_bg",type=1,typeName="Image",time=97982443,x=0,y=0,width=470,height=61,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottomLeft,file="common/background/input_bg_2.png",gridLeft=25,gridRight=25,gridTop=25,gridBottom=25,
					{
						name="send_content",type=7,typeName="EditTextView",time=97982444,x=10,y=0,width=450,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,fontSize=32,textAlign=kAlignLeft,colorRed=80,colorGreen=80,colorBlue=80,string=[[]]
					}
				},
				{
					name="send_btn",type=2,typeName="Button",time=97982401,x=0,y=0,width=128,height=58,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottomRight,file="common/button/dialog_btn_3_normal.png",file2="common/button/dialog_btn_3_press.png",
					{
						name="send_txt",type=4,typeName="Text",time=97982402,x=0,y=-2,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=32,textAlign=kAlignLeft,colorRed=240,colorGreen=230,colorBlue=210,string=[[发送]]
					}
				}
			}
		},
		{
			name="world_room_view",type=0,typeName="View",time=106136764,x=0,y=0,width=610,height=970,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,
			{
				name="title",type=0,typeName="View",time=106136765,x=0,y=0,width=186,height=75,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTop,
				{
					name="title_txt",type=4,typeName="Text",time=106136766,x=0,y=0,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,fontSize=42,textAlign=kAlignCenter,colorRed=80,colorGreen=80,colorBlue=80,string=[[深圳同城聊天室]]
				},
				{
					name="line",type=1,typeName="Image",time=106136767,x=0,y=0,width=607,height=19,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignBottom,file="common/decoration/line.png"
				},
				{
					name="check_member",type=2,typeName="Button",time=106136768,x=0,y=0,width=61,height=55,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="drawable/blank.png",file2="drawable/blank.png",
					{
						name="icon",type=1,typeName="Image",time=106136769,x=0,y=0,width=43,height=38,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="common/button/member_normal.png"
					}
				},
				{
					name="back_btn",type=2,typeName="Button",time=106136770,x=0,y=0,width=55,height=55,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="drawable/blank.png",file2="drawable/blank.png",
					{
						name="icon",type=1,typeName="Image",time=106136771,x=0,y=0,width=35,height=33,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="common/button/back_normal.png"
					}
				}
			},
			{
				name="content_view",type=0,typeName="View",time=106136772,x=0,y=0,width=200,height=770,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignCenter,
				{
					name="item_up_mask",type=1,typeName="Image",time=106136773,x=0,y=0,width=696,height=95,visible=0,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTop,file="common/decoration/item_up_mask.png"
				},
				{
					name="item_down_mask",type=1,typeName="Image",time=106136774,x=0,y=0,width=696,height=95,visible=0,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignBottom,file="common/decoration/item_down_mas.png"
				}
			},
			{
				name="bottom_view",type=0,typeName="View",time=106136775,x=0,y=0,width=200,height=105,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignBottom,
				{
					name="line",type=1,typeName="Image",time=106136776,x=0,y=0,width=607,height=19,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTop,file="common/decoration/line.png"
				},
				{
					name="send_bg",type=1,typeName="Image",time=106136777,x=0,y=0,width=470,height=61,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottomLeft,file="common/background/input_bg_2.png",gridLeft=25,gridRight=25,gridTop=25,gridBottom=25,
					{
						name="send_content",type=7,typeName="EditTextView",time=106136778,x=10,y=0,width=450,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,fontSize=32,textAlign=kAlignLeft,colorRed=80,colorGreen=80,colorBlue=80,string=[[]]
					}
				},
				{
					name="send_btn",type=2,typeName="Button",time=106136779,x=0,y=0,width=128,height=58,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottomRight,file="common/button/dialog_btn_3_normal.png",file2="common/button/dialog_btn_3_press.png",
					{
						name="send_txt",type=4,typeName="Text",time=106136780,x=0,y=-2,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=32,textAlign=kAlignLeft,colorRed=240,colorGreen=230,colorBlue=210,string=[[发送]]
					}
				}
			}
		},
		{
			name="common_room_view",type=0,typeName="View",time=97725563,x=0,y=0,width=610,height=970,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,
			{
				name="title",type=0,typeName="View",time=97729540,x=0,y=0,width=186,height=75,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTop,
				{
					name="user_name",type=4,typeName="Text",time=97729541,x=0,y=0,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,fontSize=42,textAlign=kAlignCenter,colorRed=80,colorGreen=80,colorBlue=80,string=[[NothingToLive]]
				},
				{
					name="line",type=1,typeName="Image",time=97729542,x=0,y=0,width=607,height=19,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignBottom,file="common/decoration/line.png"
				},
				{
					name="back_btn",type=2,typeName="Button",time=98946141,x=0,y=0,width=55,height=55,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="drawable/blank.png",file2="drawable/blank.png",
					{
						name="icon",type=1,typeName="Image",time=98946142,x=0,y=0,width=35,height=33,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="common/button/back_normal.png"
					}
				}
			},
			{
				name="content_view",type=0,typeName="View",time=97729613,x=0,y=0,width=200,height=770,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignCenter,
				{
					name="item_up_mask",type=1,typeName="Image",time=97729614,x=0,y=0,width=610,height=95,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTop,file="common/decoration/item_up_mask.png"
				},
				{
					name="item_down_mask",type=1,typeName="Image",time=97729615,x=0,y=0,width=696,height=95,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignBottom,file="common/decoration/item_down_mas.png"
				}
			},
			{
				name="bottom_view",type=0,typeName="View",time=97729615,x=0,y=0,width=200,height=105,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignBottom,
				{
					name="line",type=1,typeName="Image",time=97729616,x=0,y=0,width=607,height=19,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTop,file="common/decoration/line.png"
				},
				{
					name="send_bg",type=1,typeName="Image",time=97982446,x=0,y=0,width=470,height=61,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottomLeft,file="common/background/input_bg_2.png",gridLeft=25,gridRight=25,gridTop=25,gridBottom=25,
					{
						name="send_content",type=7,typeName="EditTextView",time=97982447,x=10,y=0,width=450,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,fontSize=32,textAlign=kAlignLeft,colorRed=80,colorGreen=80,colorBlue=80,string=[[]]
					}
				},
				{
					name="send_btn",type=2,typeName="Button",time=97982408,x=0,y=0,width=128,height=58,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottomRight,file="common/button/dialog_btn_3_normal.png",file2="common/button/dialog_btn_3_press.png",
					{
						name="send_txt",type=4,typeName="Text",time=97982409,x=0,y=-2,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=32,textAlign=kAlignLeft,colorRed=240,colorGreen=230,colorBlue=210,string=[[发送]]
					}
				}
			}
		}
	}
}