watchList_view=
{
	name="watchList_view",type=0,typeName="View",time=0,x=0,y=0,width=0,height=0,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,
	{
		name="watch_view_bg",type=1,typeName="Image",time=1737794,x=0,y=0,width=480,height=800,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTop,file="drawable/bg.png"
	},
	{
		name="watch_title_view",type=0,typeName="View",time=1737853,x=0,y=0,width=480,height=0,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTop,
		{
			name="watch_title_bg",type=1,typeName="Image",time=1737909,x=0,y=0,width=480,height=95,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="common/activity_center_top_title_bg.png"
		},
		{
			name="watch_title_texture_bg",type=1,typeName="Image",time=12034465,x=0,y=0,width=372,height=65,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="common/ending_bg.png",
			{
				name="Text1",type=4,typeName="Text",time=87558810,x=0,y=-5,width=200,height=65,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=32,textAlign=kAlignCenter,colorRed=255,colorGreen=230,colorBlue=180,string=[[观战]]
			}
		},
		{
			name="watch_back_btn",type=2,typeName="Button",time=1738404,x=0,y=0,width=62,height=62,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="common/ending_back.png"
		}
	},
	{
		name="watch_content_view",type=0,typeName="View",time=15822142,x=0,y=80,width=480,height=720,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,
		{
			name="ScrollContentView",type=0,typeName="ScrollView",time=88068645,x=0,y=0,width=480,height=720,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop
		}
	}
}