require("animation/animCapture")
require("animation/animCheck");
require("animation/animCoord")
require("animation/animForestall")
require("animation/animJam");
require("animation/animKill");
require("animation/animTimeout");
require("animation/broadcastMessageAnim");
require("animation/chatMessageAnim");
require("animation/consolePassAnim")
require("animation/coverGoodsAnim")
require("animation/daozhangMessageAnim")
require("animation/endingTimeUpdate")
require("animation/fadeAnim")
require("animation/gongGaoScrollAnim")
require("animation/headSmogAnim")
require("animation/headTurnAnim")
require("animation/msgScrollAnim")
require("animation/noticeAnim")
require("animation/NoticeShakeAnim")
require("animation/roomHomeAnim")
require("animation/scrollAnim")
require("animation/shockAnim")
require("animation/showMessageAnim")
require("animation/animWin");
require("animation/animLose");
require("animation/animConsoleUnlockHead");